### ISSUE TITLE
about sql

### ISSUE THREAD

**Issue by mikak00s** [AvaN0x/AdezouRP#2]
i'd like to ask if you are going to upload the sql file or do we have to use the one of Arkadia's

**Comment by AvaN0x** [comment]
Hello, I haven't done it yet because I'm often editing it, but I can prepare you one version if you want it ?

**Comment by mikak00s** [comment]
i'd really appreciate it that.

**Comment by AvaN0x** [comment]
Ok, I start working on it

**Comment by AvaN0x** [comment]
Here is the file you asked for :) . It will still contain some unused tables but I haven't got the time to clear all of them.
It will be done later
[Commit](https://github.com/AvaN0x/AdezouRP/commit/09f2e1f442889cdc4cc5133002fc8272bf88fc12)

**Comment by mikak00s** [comment]
Alright, Thanks mate.

**Comment by ethanke** [comment]
Hey,

I got some error with "ban_list.*" table and inventories when starting the server

**Comment by AvaN0x** [comment]
Hello, can you send me them ?

**Comment by AvaN0x** [comment]
> Hey,
> 
> I got some error with "ban_list.*" table and inventories when starting the server

This should now be good for you
[Commit](https://github.com/AvaN0x/AdezouRP/commit/b59a92a5ff38dbd6c79b052a33a600b240936ffe)
